Fix support for Aruba AOS CX devices
Trying to use an Aruba AOS CX device with NGS, using the "aruba_os" device
type, fails with:

    Netmiko connection error: {'ip': ..., 'device_type': 'aruba_os'},
    error: Failed to enter configuration mode.

The current support for Aruba AOS CX devices actually relies on a Netmiko
class for Aruba OS, "aruba_os", which is an OS for wireless controllers,
not for switches.  In particular, the config pattern is wrong:
"(config) #" vs "(config)#".

As far as we can tell, this couldn't possibly have worked in the past in
NGS, because the config pattern of aruba_os in Netmiko hasn't changed
since 2016.

Netmiko 4.4.0 introduced support for AOS CX devices, so let's use that
instead.

Tested with a Aruba 8325-48Y8C switch running ArubaOS-CX version GL.10.09.1020

Signed-off-by: Baptiste Jonglez <baptiste.jonglez@inria.fr>
Change-Id: I71b1ea9d72f8a0e8fb2ebb0c9f7c0583f311609a