Fix batching error due to outdated etcd3gw
Testing the new batching feature ended up crashing Neutron:

      File "/usr/local/lib/python3.9/dist-packages/networking_generic_switch/batching.py", line 325, in __init__
        etcd_client = etcd3gw.client(
    TypeError: client() got an unexpected keyword argument 'api_path'

This new feature needs etcd3gw 2.1.0, update minimum version of dependency
accordingly.

Note that this is only an issue when reusing an existing environment or
having to compose with other dependency constraints.  Simply installing
the most recent version of etcd3gw works as expected.

Change-Id: Ie6ecf781fde990ffbce420904978fe5a9fb1e400